---
# tasks file for add_domain_computer
- name: Set windows hostname
  set_fact:
    windows_hostname: "{{ inventory_hostname | regex_replace('(^.*)\\.ec2\\.internal$', 
    '\\1') }}"

- name: Set DNS lookup addresses
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - "{{ dns_ip1 }}"
    - "{{ dns_ip2 }}"
    
- name: add computer to domain
  win_domain_membership:
    hostname: "{{ windows_hostname }}"
    state: "{{ ad_computer_state }}"
    domain_ou_path: "{{ ad_ou_path }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    dns_domain_name: "{{ ad_domain_server }}"
  register: domain_state

- win_reboot:
  when: domain_state.reboot_required

- name: Add empire_admin to RDU group
  win_group_membership:
    name: Remote Desktop Users
    members:
      - empire\empire_admin
    state: present